services:
  laravel:
    build: ./pusher-server-laravel
    volumes:
      - ./pusher-server-laravel:/var/www
    ports:
      - "9000:9000"
    environment:
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - PUSHER_HOST=${PUSHER_HOST}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "php", "artisan", "serve"]
      interval: 10s
      timeout: 5s
      retries: 3

  python-client:
    build: ./pusher-client-python
    depends_on:
      laravel:
        condition: service_healthy

    volumes:
      - ./pusher-client-python:/app
    environment:
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_KEY=${PUSHER_APP_KEY}
      - PUSHER_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_CLUSTER=${PUSHER_APP_CLUSTER}
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  app-network:
    driver: bridge
